const fs = require('fs');
const path = require('path');

const cl_finals = [
    {"year": "2023/24", "winner": "Real Madrid", "runnerUp": "Borussia Dortmund", "score": "2-0", "stadium": "Wembley Stadium, Londra", "coach": "Carlo Ancelotti", "stats": {"possession": "54% - 46%", "shots": "13 - 13", "shotsOnTarget": "6 - 3", "corners": "8 - 9", "fouls": "10 - 11"}, "roster": ["Thibaut Courtois", "Dani Carvajal", "Antonio Rüdiger", "Nacho", "Ferland Mendy", "Federico Valverde", "Eduardo Camavinga", "Toni Kroos", "Jude Bellingham", "Rodrygo", "Vinicius Junior"]},
    {"year": "2022/23", "winner": "Manchester City", "runnerUp": "Inter", "score": "1-0", "stadium": "Atatürk Olympic Stadium, Istanbul", "coach": "Pep Guardiola", "stats": {"possession": "56% - 44%", "shots": "7 - 14", "shotsOnTarget": "4 - 6", "corners": "2 - 4", "fouls": "11 - 17"}, "roster": ["Ederson", "Manuel Akanji", "Ruben Dias", "Nathan Ake", "John Stones", "Rodri", "Bernardo Silva", "Kevin De Bruyne", "Ilkay Gündogan", "Jack Grealish", "Erling Haaland"]},
    {"year": "2021/22", "winner": "Real Madrid", "runnerUp": "Liverpool", "score": "1-0", "stadium": "Stade de France, Parigi", "coach": "Carlo Ancelotti", "stats": {"possession": "46% - 54%", "shots": "4 - 24", "shotsOnTarget": "2 - 9", "corners": "2 - 6", "fouls": "7 - 8"}, "roster": ["Thibaut Courtois", "Dani Carvajal", "Eder Militao", "David Alaba", "Ferland Mendy", "Casemiro", "Toni Kroos", "Luka Modric", "Federico Valverde", "Vinicius Junior", "Karim Benzema"]},
    {"year": "2020/21", "winner": "Chelsea", "runnerUp": "Manchester City", "score": "1-0", "stadium": "Estádio do Dragão, Porto", "coach": "Thomas Tuchel", "stats": {"possession": "39% - 61%", "shots": "8 - 7", "shotsOnTarget": "2 - 1", "corners": "1 - 3", "fouls": "13 - 14"}, "roster": ["Edouard Mendy", "Cesar Azpilicueta", "Thiago Silva", "Antonio Rüdiger", "Reece James", "Jorginho", "N'Golo Kanté", "Ben Chilwell", "Mason Mount", "Kai Havertz", "Timo Werner"]},
    {"year": "2019/20", "winner": "Bayern Munich", "runnerUp": "Paris Saint-Germain", "score": "1-0", "stadium": "Estádio da Luz, Lisbona", "coach": "Hans-Dieter Flick", "stats": {"possession": "62% - 38%", "shots": "12 - 9", "shotsOnTarget": "2 - 3", "corners": "4 - 4", "fouls": "22 - 16"}, "roster": ["Manuel Neuer", "Joshua Kimmich", "Jerome Boateng", "David Alaba", "Alphonso Davies", "Leon Goretzka", "Thiago Alcantara", "Serge Gnabry", "Thomas Müller", "Kingsley Coman", "Robert Lewandowski"]},
    {"year": "2018/19", "winner": "Liverpool", "runnerUp": "Tottenham Hotspur", "score": "2-0", "stadium": "Wanda Metropolitano, Madrid", "coach": "Jürgen Klopp", "stats": {"possession": "35% - 65%", "shots": "14 - 16", "shotsOnTarget": "3 - 8", "corners": "9 - 8", "fouls": "6 - 5"}, "roster": ["Alisson", "Trent Alexander-Arnold", "Joel Matip", "Virgil van Dijk", "Andrew Robertson", "Jordan Henderson", "Fabinho", "Georginio Wijnaldum", "Mohamed Salah", "Roberto Firmino", "Sadio Mané"]},
    {"year": "2017/18", "winner": "Real Madrid", "runnerUp": "Liverpool", "score": "3-1", "stadium": "NSC Olimpiyskiy, Kiev", "coach": "Zinedine Zidane", "stats": {"possession": "62% - 38%", "shots": "14 - 13", "shotsOnTarget": "5 - 2", "corners": "9 - 5", "fouls": "5 - 18"}, "roster": ["Keylor Navas", "Dani Carvajal", "Raphael Varane", "Sergio Ramos", "Marcelo", "Casemiro", "Luka Modric", "Toni Kroos", "Isco", "Karim Benzema", "Cristiano Ronaldo"]},
    {"year": "2016/17", "winner": "Real Madrid", "runnerUp": "Juventus", "score": "4-1", "stadium": "Millennium Stadium, Cardiff", "coach": "Zinedine Zidane", "stats": {"possession": "56% - 44%", "shots": "18 - 9", "shotsOnTarget": "5 - 4", "corners": "1 - 1", "fouls": "18 - 23"}, "roster": ["Keylor Navas", "Dani Carvajal", "Raphael Varane", "Sergio Ramos", "Marcelo", "Casemiro", "Luka Modric", "Toni Kroos", "Isco", "Karim Benzema", "Cristiano Ronaldo"]},
    {"year": "2015/16", "winner": "Real Madrid", "runnerUp": "Atletico Madrid", "score": "1-1 (5-3 dcr)", "stadium": "San Siro, Milano", "coach": "Zinedine Zidane", "stats": {"possession": "46% - 54%", "shots": "25 - 17", "shotsOnTarget": "8 - 4", "corners": "7 - 6", "fouls": "18 - 16"}, "roster": ["Keylor Navas", "Dani Carvajal", "Pepe", "Sergio Ramos", "Marcelo", "Casemiro", "Luka Modric", "Toni Kroos", "Gareth Bale", "Karim Benzema", "Cristiano Ronaldo"]},
    {"year": "2014/15", "winner": "Barcelona", "runnerUp": "Juventus", "score": "3-1", "stadium": "Olympiastadion, Berlino", "coach": "Luis Enrique", "stats": {"possession": "62% - 38%", "shots": "18 - 14", "shotsOnTarget": "8 - 6", "corners": "8 - 8", "fouls": "12 - 24"}, "roster": ["Marc-André ter Stegen", "Dani Alves", "Gerard Piqué", "Javier Mascherano", "Jordi Alba", "Sergio Busquets", "Ivan Rakitic", "Andres Iniesta", "Lionel Messi", "Luis Suarez", "Neymar"]},
    {"year": "2013/14", "winner": "Real Madrid", "runnerUp": "Atletico Madrid", "score": "4-1 (dts)", "stadium": "Estádio da Luz, Lisbona", "coach": "Carlo Ancelotti", "stats": {"possession": "60% - 40%", "shots": "21 - 10", "shotsOnTarget": "9 - 4", "corners": "9 - 9", "fouls": "19 - 27"}, "roster": ["Iker Casillas", "Dani Carvajal", "Sergio Ramos", "Raphael Varane", "Fabio Coentrao", "Sami Khedira", "Luka Modric", "Angel Di Maria", "Gareth Bale", "Karim Benzema", "Cristiano Ronaldo"]},
    {"year": "2012/13", "winner": "Bayern Munich", "runnerUp": "Borussia Dortmund", "score": "2-1", "stadium": "Wembley Stadium, Londra", "coach": "Jupp Heynckes", "stats": {"possession": "57% - 43%", "shots": "14 - 12", "shotsOnTarget": "9 - 8", "corners": "8 - 6", "fouls": "10 - 13"}, "roster": ["Manuel Neuer", "Philipp Lahm", "Jerome Boateng", "Dante", "David Alaba", "Javi Martinez", "Bastian Schweinsteiger", "Arjen Robben", "Thomas Müller", "Franck Ribery", "Mario Mandzukic"]},
    {"year": "2011/12", "winner": "Chelsea", "runnerUp": "Bayern Munich", "score": "1-1 (4-3 dcr)", "stadium": "Allianz Arena, Monaco", "coach": "Roberto Di Matteo", "stats": {"possession": "44% - 56%", "shots": "9 - 35", "shotsOnTarget": "3 - 7", "corners": "1 - 20", "fouls": "26 - 14"}, "roster": ["Petr Cech", "Jose Bosingwa", "David Luiz", "Gary Cahill", "Ashley Cole", "John Obi Mikel", "Frank Lampard", "Salomon Kalou", "Juan Mata", "Ryan Bertrand", "Didier Drogba"]},
    {"year": "2010/11", "winner": "Barcelona", "runnerUp": "Manchester United", "score": "3-1", "stadium": "Wembley Stadium, Londra", "coach": "Pep Guardiola", "stats": {"possession": "63% - 37%", "shots": "19 - 4", "shotsOnTarget": "12 - 1", "corners": "6 - 0", "fouls": "5 - 16"}, "roster": ["Victor Valdes", "Dani Alves", "Javier Mascherano", "Gerard Piqué", "Eric Abidal", "Sergio Busquets", "Xavi", "Andres Iniesta", "David Villa", "Lionel Messi", "Pedro"]},
    {"year": "2009/10", "winner": "Inter", "runnerUp": "Bayern Munich", "score": "2-0", "stadium": "Santiago Bernabéu, Madrid", "coach": "José Mourinho", "stats": {"possession": "32% - 68%", "shots": "11 - 21", "shotsOnTarget": "7 - 6", "corners": "2 - 5", "fouls": "13 - 16"}, "roster": ["Julio Cesar", "Maicon", "Lucio", "Walter Samuel", "Cristian Chivu", "Javier Zanetti", "Esteban Cambiasso", "Wesley Sneijder", "Samuel Eto'o", "Diego Milito", "Goran Pandev"]},
    {"year": "2008/09", "winner": "Barcelona", "runnerUp": "Manchester United", "score": "2-0", "stadium": "Stadio Olimpico, Roma", "coach": "Pep Guardiola", "stats": {"possession": "51% - 49%", "shots": "11 - 12", "shotsOnTarget": "8 - 2", "corners": "4 - 7", "fouls": "17 - 10"}, "roster": ["Victor Valdes", "Carles Puyol", "Yaya Touré", "Gerard Piqué", "Sylvinho", "Sergio Busquets", "Xavi", "Andres Iniesta", "Lionel Messi", "Samuel Eto'o", "Thierry Henry"]},
    {"year": "2007/08", "winner": "Manchester United", "runnerUp": "Chelsea", "score": "1-1 (6-5 dcr)", "stadium": "Luzhniki Stadium, Mosca", "coach": "Alex Ferguson", "stats": {"possession": "58% - 42%", "shots": "12 - 24", "shotsOnTarget": "5 - 3", "corners": "5 - 8", "fouls": "22 - 24"}, "roster": ["Edwin van der Sar", "Wes Brown", "Rio Ferdinand", "Nemanja Vidic", "Patrice Evra", "Owen Hargreaves", "Paul Scholes", "Michael Carrick", "Cristiano Ronaldo", "Wayne Rooney", "Carlos Tevez"]},
    {"year": "2006/07", "winner": "Milan", "runnerUp": "Liverpool", "score": "2-1", "stadium": "Stadio Olimpico, Atene", "coach": "Carlo Ancelotti", "stats": {"possession": "53% - 47%", "shots": "5 - 12", "shotsOnTarget": "3 - 4", "corners": "4 - 6", "fouls": "14 - 26"}, "roster": ["Dida", "Massimo Oddo", "Alessandro Nesta", "Paolo Maldini", "Marek Jankulovski", "Gennaro Gattuso", "Andrea Pirlo", "Massimo Ambrosini", "Clarence Seedorf", "Kaka", "Filippo Inzaghi"]},
    {"year": "2005/06", "winner": "Barcelona", "runnerUp": "Arsenal", "score": "2-1", "stadium": "Stade de France, Parigi", "coach": "Frank Rijkaard", "stats": {"possession": "64% - 36%", "shots": "18 - 8", "shotsOnTarget": "9 - 5", "corners": "3 - 4", "fouls": "19 - 16"}, "roster": ["Victor Valdes", "Oleguer", "Carles Puyol", "Rafael Marquez", "Giovanni van Bronckhorst", "Edmilson", "Deco", "Mark van Bommel", "Ludovic Giuly", "Samuel Eto'o", "Ronaldinho"]},
    {"year": "2004/05", "winner": "Liverpool", "runnerUp": "Milan", "score": "3-3 (3-2 dcr)", "stadium": "Atatürk Olympic Stadium, Istanbul", "coach": "Rafael Benitez", "stats": {"possession": "45% - 55%", "shots": "15 - 22", "shotsOnTarget": "7 - 10", "corners": "4 - 10", "fouls": "23 - 16"}, "roster": ["Jerzy Dudek", "Steve Finnan", "Jamie Carragher", "Sami Hyypia", "Djimi Traore", "Xabi Alonso", "Luis Garcia", "Steven Gerrard", "John Arne Riise", "Harry Kewell", "Milan Baros"]},
    {"year": "2003/04", "winner": "Porto", "runnerUp": "Monaco", "score": "3-0", "stadium": "Arena AufSchalke, Gelsenkirchen", "coach": "José Mourinho", "stats": {"possession": "44% - 56%", "shots": "4 - 0", "shotsOnTarget": "3 - 0", "corners": "2 - 1", "fouls": "20 - 13"}, "roster": ["Vitor Baia", "Paulo Ferreira", "Jorge Costa", "Ricardo Carvalho", "Nuno Valente", "Costinha", "Pedro Mendes", "Maniche", "Deco", "Derlei", "Carlos Alberto"]},
    {"year": "2002/03", "winner": "Milan", "runnerUp": "Juventus", "score": "0-0 (3-2 dcr)", "stadium": "Old Trafford, Manchester", "coach": "Carlo Ancelotti", "stats": {"possession": "48% - 52%", "shots": "14 - 11", "shotsOnTarget": "3 - 2", "corners": "10 - 5", "fouls": "23 - 34"}, "roster": ["Dida", "Alessandro Costacurta", "Alessandro Nesta", "Paolo Maldini", "Kakha Kaladze", "Gennaro Gattuso", "Andrea Pirlo", "Clarence Seedorf", "Rui Costa", "Andriy Shevchenko", "Filippo Inzaghi"]},
    {"year": "2001/02", "winner": "Real Madrid", "runnerUp": "Bayer Leverkusen", "score": "2-1", "stadium": "Hampden Park, Glasgow", "coach": "Vicente del Bosque", "roster": ["Cesar", "Michel Salgado", "Fernando Hierro", "Ivan Helguera", "Roberto Carlos", "Claude Makelele", "Luis Figo", "Santiago Solari", "Zinedine Zidane", "Raul", "Fernando Morientes"]},
    {"year": "2000/01", "winner": "Bayern Munich", "runnerUp": "Valencia", "score": "1-1 (5-4 dcr)", "stadium": "San Siro, Milano", "coach": "Ottmar Hitzfeld", "roster": ["Oliver Kahn", "Samuel Kuffour", "Patrik Andersson", "Thomas Linke", "Willy Sagnol", "Bixente Lizarazu", "Owen Hargreaves", "Stefan Effenberg", "Mehmet Scholl", "Hasan Salihamidzic", "Giovane Elber"]},
    {"year": "1999/00", "winner": "Real Madrid", "runnerUp": "Valencia", "score": "3-0", "stadium": "Stade de France, Parigi", "coach": "Vicente del Bosque", "roster": ["Iker Casillas", "Aitor Karanka", "Ivan Helguera", "Ivan Campo", "Michel Salgado", "Roberto Carlos", "Fernando Redondo", "Steve McManaman", "Raul", "Fernando Morientes", "Nicolas Anelka"]},
    {"year": "1998/99", "winner": "Manchester United", "runnerUp": "Bayern Munich", "score": "2-1", "stadium": "Camp Nou, Barcellona", "coach": "Alex Ferguson", "roster": ["Peter Schmeichel", "Gary Neville", "Ronny Johnsen", "Jaap Stam", "Denis Irwin", "Ryan Giggs", "David Beckham", "Nicky Butt", "Jesper Blomqvist", "Dwight Yorke", "Andy Cole"]},
    {"year": "1997/98", "winner": "Real Madrid", "runnerUp": "Juventus", "score": "1-0", "stadium": "Amsterdam Arena, Amsterdam", "coach": "Jupp Heynckes", "roster": ["Bodo Illgner", "Christian Panucci", "Manuel Sanchis", "Fernando Hierro", "Roberto Carlos", "Fernando Redondo", "Christian Karembeu", "Clarence Seedorf", "Raul", "Fernando Morientes", "Predrag Mijatovic"]},
    {"year": "1996/97", "winner": "Borussia Dortmund", "runnerUp": "Juventus", "score": "3-1", "stadium": "Olympiastadion, Monaco", "coach": "Ottmar Hitzfeld", "roster": ["Stefan Klos", "Jürgen Kohler", "Matthias Sammer", "Martin Kree", "Stefan Reuter", "Jörg Heinrich", "Paul Lambert", "Paulo Sousa", "Andreas Möller", "Karl-Heinz Riedle", "Stephane Chapuisat"]},
    {"year": "1995/96", "winner": "Juventus", "runnerUp": "Ajax", "score": "1-1 (4-2 dcr)", "stadium": "Stadio Olimpico, Roma", "coach": "Marcello Lippi", "roster": ["Angelo Peruzzi", "Moreno Torricelli", "Pietro Vierchowod", "Ciro Ferrara", "Gianluca Pessotto", "Antonio Conte", "Paulo Sousa", "Didier Deschamps", "Alessandro Del Piero", "Gianluca Vialli", "Fabrizio Ravanelli"]},
    {"year": "1994/95", "winner": "Ajax", "runnerUp": "Milan", "score": "1-0", "stadium": "Ernst-Happel-Stadion, Vienna", "coach": "Louis van Gaal", "roster": ["Edwin van der Sar", "Michael Reiziger", "Danny Blind", "Frank Rijkaard", "Frank de Boer", "Clarence Seedorf", "Edgar Davids", "Ronald de Boer", "Jari Litmanen", "Finidi George", "Marc Overmars"]},
    {"year": "1993/94", "winner": "Milan", "runnerUp": "Barcelona", "score": "4-0", "stadium": "Olympiako Stadio, Atene", "coach": "Fabio Capello", "roster": ["Sebastiano Rossi", "Mauro Tassotti", "Filippo Galli", "Paolo Maldini", "Christian Panucci", "Zvonimir Boban", "Demetrio Albertini", "Marcel Desailly", "Roberto Donadoni", "Dejan Savicevic", "Daniele Massaro"]},
    {"year": "1992/93", "winner": "Olympique Marseille", "runnerUp": "Milan", "score": "1-0", "stadium": "Olympiastadion, Monaco", "coach": "Raymond Goethals", "roster": ["Fabien Barthez", "Jocelyn Angloma", "Basile Boli", "Marcel Desailly", "Eric Di Meco", "Didier Deschamps", "Franck Sauzée", "Abedi Pelé", "Rudi Völler", "Alen Boksic", "Jean-Jacques Eydelie"]},
    {"year": "1991/92", "winner": "Barcelona", "runnerUp": "Sampdoria", "score": "1-0 (dts)", "stadium": "Wembley Stadium, Londra", "coach": "Johan Cruyff", "roster": ["Andoni Zubizarreta", "Nando", "Ronald Koeman", "Albert Ferrer", "Juan Carlos", "Jose Mari Bakero", "Josep Guardiola", "Eusebio Sacristan", "Michael Laudrup", "Hristo Stoichkov", "Julio Salinas"]},
    {"year": "1990/91", "winner": "Red Star Belgrade", "runnerUp": "Olympique Marseille", "score": "0-0 (5-3 dcr)", "stadium": "Stadio San Nicola, Bari", "coach": "Ljupko Petrovic", "roster": ["Stevan Stojanovic", "Slobodan Marovic", "Ilija Najdoski", "Refik Sabanadzovic", "Miodrag Belodedici", "Vladimir Jugovic", "Sinisa Mihajlovic", "Robert Prosinecki", "Dejan Savicevic", "Darko Pancev", "Dragisa Binic"]},
    {"year": "1989/90", "winner": "Milan", "runnerUp": "Benfica", "score": "1-0", "stadium": "Praterstadion, Vienna", "coach": "Arrigo Sacchi", "roster": ["Giovanni Galli", "Mauro Tassotti", "Alessandro Costacurta", "Franco Baresi", "Paolo Maldini", "Angelo Colombo", "Frank Rijkaard", "Carlo Ancelotti", "Alberigo Evani", "Ruud Gullit", "Marco van Basten"]},
    {"year": "1988/89", "winner": "Milan", "runnerUp": "Steaua Bucuresti", "score": "4-0", "stadium": "Camp Nou, Barcellona", "coach": "Arrigo Sacchi", "roster": ["Giovanni Galli", "Mauro Tassotti", "Alessandro Costacurta", "Franco Baresi", "Paolo Maldini", "Angelo Colombo", "Frank Rijkaard", "Carlo Ancelotti", "Roberto Donadoni", "Ruud Gullit", "Marco van Basten"]},
    {"year": "1987/88", "winner": "PSV Eindhoven", "runnerUp": "Benfica", "score": "0-0 (6-5 dcr)", "stadium": "Neckarstadion, Stoccarda", "coach": "Guus Hiddink", "roster": ["Hans van Breukelen", "Eric Gerets", "Ivan Nielsen", "Ronald Koeman", "Jan Heintze", "Berry van Aerle", "Edward Linskens", "Gerald Vanenburg", "Wim Kieft", "Sören Lerby", "Hans Gillhaus"]},
    {"year": "1986/87", "winner": "Porto", "runnerUp": "Bayern Munich", "score": "2-1", "stadium": "Praterstadion, Vienna", "coach": "Artur Jorge", "roster": ["Jozef Mlynarczyk", "Joao Pinto", "Celso", "Eduardo Luis", "Augusto Inacio", "Quim", "Jaime Magalhaes", "Antonio Sousa", "André", "Paulo Futre", "Rabah Madjer"]},
    {"year": "1985/86", "winner": "Steaua Bucuresti", "runnerUp": "Barcelona", "score": "0-0 (2-0 dcr)", "stadium": "Ramón Sánchez Pizjuán, Siviglia", "coach": "Emerich Jenei", "roster": ["Helmuth Duckadam", "Stefan Iovan", "Adrian Bumbescu", "Miodrag Belodedici", "Ilie Barbulescu", "Lucian Balan", "Gavril Balint", "László Bölöni", "Mihail Majearu", "Marius Lacatus", "Victor Piturca"]},
    {"year": "1984/85", "winner": "Juventus", "runnerUp": "Liverpool", "score": "1-0", "stadium": "Heysel Stadium, Bruxelles", "coach": "Giovanni Trapattoni", "roster": ["Stefano Tacconi", "Luciano Favero", "Antonio Cabrini", "Massimo Bonini", "Sergio Brio", "Gaetano Scirea", "Massimo Briaschi", "Marco Tardelli", "Paolo Rossi", "Michel Platini", "Zbigniew Boniek"]},
    {"year": "1983/84", "winner": "Liverpool", "runnerUp": "Roma", "score": "1-1 (4-2 dcr)", "stadium": "Stadio Olimpico, Roma", "coach": "Joe Fagan", "roster": ["Bruce Grobbelaar", "Phil Neal", "Mark Lawrenson", "Alan Hansen", "Alan Kennedy", "Craig Johnston", "Sammy Lee", "Graeme Souness", "Ronnie Whelan", "Kenny Dalglish", "Ian Rush"]},
    {"year": "1982/83", "winner": "Hamburg", "runnerUp": "Juventus", "score": "1-0", "stadium": "Olympiako Stadio, Atene", "coach": "Ernst Happel", "roster": ["Uli Stein", "Manfred Kaltz", "Ditmar Jakobs", "Holger Hieronymus", "Bernd Wehmeyer", "Jürgen Groh", "Wolfgang Rolff", "Felix Magath", "Jürgen Milewski", "Horst Hrubesch", "Lars Bastrup"]},
    {"year": "1981/82", "winner": "Aston Villa", "runnerUp": "Bayern Munich", "score": "1-0", "stadium": "De Kuip, Rotterdam", "coach": "Tony Barton", "roster": ["Jimmy Rimmer", "Kenny Swain", "Ken McNaught", "Allan Evans", "Gary Williams", "Dennis Mortimer", "Des Bremner", "Gordon Cowans", "Tony Morley", "Gary Shaw", "Peter Withe"]},
    {"year": "1980/81", "winner": "Liverpool", "runnerUp": "Real Madrid", "score": "1-0", "stadium": "Parc des Princes, Parigi", "coach": "Bob Paisley", "roster": ["Ray Clemence", "Phil Neal", "Alan Hansen", "Colin Irwin", "Alan Kennedy", "Sammy Lee", "Graeme Souness", "Terry McDermott", "Ray Kennedy", "Kenny Dalglish", "David Johnson"]},
    {"year": "1979/80", "winner": "Nottingham Forest", "runnerUp": "Hamburg", "score": "1-0", "stadium": "Santiago Bernabéu, Madrid", "coach": "Brian Clough", "roster": ["Peter Shilton", "Viv Anderson", "Frank Gray", "Larry Lloyd", "Kenny Burns", "Martin O'Neill", "Ian Bowyer", "Gary Mills", "John McGovern", "Garry Birtles", "John Robertson"]},
    {"year": "1978/79", "winner": "Nottingham Forest", "runnerUp": "Malmö FF", "score": "1-0", "stadium": "Olympiastadion, Monaco", "coach": "Brian Clough", "roster": ["Peter Shilton", "Viv Anderson", "Frank Clark", "Larry Lloyd", "Kenny Burns", "Trevor Francis", "Ian Bowyer", "Gary Birtles", "John McGovern", "Tony Woodcock", "John Robertson"]},
    {"year": "1977/78", "winner": "Liverpool", "runnerUp": "Club Brugge", "score": "1-0", "stadium": "Wembley Stadium, Londra", "coach": "Bob Paisley", "roster": ["Ray Clemence", "Phil Neal", "Phil Thompson", "Alan Hansen", "Ray Kennedy", "Emlyn Hughes", "Graeme Souness", "Terry McDermott", "Jimmy Case", "Kenny Dalglish", "David Fairclough"]},
    {"year": "1976/77", "winner": "Liverpool", "runnerUp": "Borussia M.Gladbach", "score": "3-1", "stadium": "Stadio Olimpico, Roma", "coach": "Bob Paisley", "roster": ["Ray Clemence", "Phil Neal", "Tommy Smith", "Emlyn Hughes", "Joey Jones", "Ian Callaghan", "Terry McDermott", "Ray Kennedy", "Jimmy Case", "Kevin Keegan", "Steve Heighway"]},
    {"year": "1975/76", "winner": "Bayern Munich", "runnerUp": "Saint-Étienne", "score": "1-0", "stadium": "Hampden Park, Glasgow", "coach": "Dettmar Cramer", "roster": ["Sepp Maier", "Johnny Hansen", "Udo Horsmann", "Hans-Georg Schwarzenbeck", "Franz Beckenbauer", "Bernd Dürnberger", "Franz Roth", "Jupp Kapellmann", "Karl-Heinz Rummenigge", "Gerd Müller", "Uli Hoeness"]},
    {"year": "1974/75", "winner": "Bayern Munich", "runnerUp": "Leeds United", "score": "2-0", "stadium": "Parc des Princes, Parigi", "coach": "Dettmar Cramer", "roster": ["Sepp Maier", "Bernd Dürnberger", "Hans-Georg Schwarzenbeck", "Franz Beckenbauer", "Björn Andersson", "Rainer Zobel", "Franz Roth", "Jupp Kapellmann", "Conny Torstensson", "Gerd Müller", "Uli Hoeness"]},
    {"year": "1973/74", "winner": "Bayern Munich", "runnerUp": "Atletico Madrid", "score": "4-0", "stadium": "Heysel Stadium, Bruxelles", "coach": "Udo Lattek", "roster": ["Sepp Maier", "Johnny Hansen", "Paul Breitner", "Hans-Georg Schwarzenbeck", "Franz Beckenbauer", "Franz Roth", "Conny Torstensson", "Rainer Zobel", "Gerd Müller", "Uli Hoeness", "Jupp Kapellmann"]},
    {"year": "1972/73", "winner": "Ajax", "runnerUp": "Juventus", "score": "1-0", "stadium": "Crvena Zvezda Stadium, Belgrado", "coach": "Stefan Kovacs", "roster": ["Heinz Stuy", "Wim Suurbier", "Barry Hulshoff", "Horst Blankenburg", "Ruud Krol", "Johan Neeskens", "Arie Haan", "Gerrie Mühren", "Sjaak Swart", "Johan Cruyff", "Piet Keizer"]},
    {"year": "1971/72", "winner": "Ajax", "runnerUp": "Inter", "score": "2-0", "stadium": "De Kuip, Rotterdam", "coach": "Stefan Kovacs", "roster": ["Heinz Stuy", "Wim Suurbier", "Barry Hulshoff", "Horst Blankenburg", "Ruud Krol", "Johan Neeskens", "Arie Haan", "Gerrie Mühren", "Sjaak Swart", "Johan Cruyff", "Piet Keizer"]},
    {"year": "1970/71", "winner": "Ajax", "runnerUp": "Panathinaikos", "score": "2-0", "stadium": "Wembley Stadium, Londra", "coach": "Rinus Michels", "roster": ["Heinz Stuy", "Wim Suurbier", "Barry Hulshoff", "Velibor Vasovic", "Ruud Krol", "Johan Neeskens", "Nico Rijnders", "Gerrie Mühren", "Sjaak Swart", "Johan Cruyff", "Dick van Dijk"]},
    {"year": "1969/70", "winner": "Feyenoord", "runnerUp": "Celtic", "score": "2-1 (dts)", "stadium": "San Siro, Milano", "coach": "Ernst Happel", "roster": ["Eddy Pieters Graafland", "Piet Romeijn", "Rinus Israel", "Theo Laseroms", "Theo van Duivenbode", "Franz Hasil", "Wim Jansen", "Willem van Hanegem", "Henk Wery", "Ove Kindvall", "Coen Moulijn"]},
    {"year": "1968/69", "winner": "Milan", "runnerUp": "Ajax", "score": "4-1", "stadium": "Santiago Bernabéu, Madrid", "coach": "Nereo Rocco", "roster": ["Fabio Cudicini", "Angelo Anquilletti", "Karl-Heinz Schnellinger", "Roberto Rosato", "Saul Malatrasi", "Giovanni Trapattoni", "Kurt Hamrin", "Lodovico Delvecchio", "Angelo Sormani", "Gianni Rivera", "Pierino Prati"]},
    {"year": "1967/68", "winner": "Manchester United", "runnerUp": "Benfica", "score": "4-1 (dts)", "stadium": "Wembley Stadium, Londra", "coach": "Matt Busby", "roster": ["Alex Stepney", "Shay Brennan", "Bill Foulkes", "David Sadler", "Tony Dunne", "Pat Crerand", "Bobby Charlton", "Nobby Stiles", "George Best", "Brian Kidd", "John Aston"]},
    {"year": "1966/67", "winner": "Celtic", "runnerUp": "Inter", "score": "2-1", "stadium": "Estádio Nacional, Lisbona", "coach": "Jock Stein", "roster": ["Ronnie Simpson", "Jim Craig", "Tommy Gemmell", "Bobby Murdoch", "Billy McNeill", "John Clark", "Jimmy Johnstone", "Willie Wallace", "Stevie Chalmers", "Bertie Auld", "Bobby Lennox"]},
    {"year": "1965/66", "winner": "Real Madrid", "runnerUp": "Partizan", "score": "2-1", "stadium": "Heysel Stadium, Bruxelles", "coach": "Miguel Muñoz", "roster": ["Jose Araquistain", "Pachin", "Pedro de Felipe", "Ignacio Zoco", "Manuel Sanchis", "Pirri", "Manuel Velazquez", "Fernando Serena", "Amancio Amaro", "Ramon Grosso", "Paco Gento"]},
    {"year": "1964/65", "winner": "Inter", "runnerUp": "Benfica", "score": "1-0", "stadium": "San Siro, Milano", "coach": "Helenio Herrera", "roster": ["Giuliano Sarti", "Tarcisio Burgnich", "Giacinto Facchetti", "Gianfranco Bedin", "Aristide Guarneri", "Armando Picchi", "Jair da Costa", "Sandro Mazzola", "Joaquin Peiró", "Luis Suárez", "Mario Corso"]},
    {"year": "1963/64", "winner": "Inter", "runnerUp": "Real Madrid", "score": "3-1", "stadium": "Praterstadion, Vienna", "coach": "Helenio Herrera", "roster": ["Giuliano Sarti", "Tarcisio Burgnich", "Giacinto Facchetti", "Carlo Tagnin", "Aristide Guarneri", "Armando Picchi", "Jair da Costa", "Sandro Mazzola", "Aurelio Milani", "Luis Suárez", "Mario Corso"]},
    {"year": "1962/63", "winner": "Milan", "runnerUp": "Benfica", "score": "2-1", "stadium": "Wembley Stadium, Londra", "coach": "Nereo Rocco", "roster": ["Giorgio Ghezzi", "Mario David", "Mario Trebbi", "Victor Benitez", "Cesare Maldini", "Giovanni Trapattoni", "Gino Pivatelli", "Dino Sani", "José Altafini", "Gianni Rivera", "Bruno Mora"]},
    {"year": "1961/62", "winner": "Benfica", "runnerUp": "Real Madrid", "score": "5-3", "stadium": "Olympisch Stadion, Amsterdam", "coach": "Béla Guttmann", "roster": ["Costa Pereira", "João Jurado", "Germano", "Angelo Martins", "Domiciano Cavém", "Fernando Cruz", "José Augusto", "Eusébio", "José Águas", "Mário Coluna", "António Simões"]},
    {"year": "1960/61", "winner": "Benfica", "runnerUp": "Barcelona", "score": "3-2", "stadium": "Wankdorf Stadium, Berna", "coach": "Béla Guttmann", "roster": ["Costa Pereira", "Mário João", "Germano", "Angelo Martins", "José Neto", "Fernando Cruz", "José Augusto", "Joaquim Santana", "José Águas", "Mário Coluna", "Domiciano Cavém"]},
    {"year": "1959/60", "winner": "Real Madrid", "runnerUp": "Eintracht Frankfurt", "score": "7-3", "stadium": "Hampden Park, Glasgow", "coach": "Miguel Muñoz", "roster": ["Rogelio Dominguez", "Marquitos", "Josamaria Zarraga", "Pachin", "José Maria Vidal", "Ruiz", "Canario", "Luis del Sol", "Alfredo Di Stefano", "Ferenc Puskas", "Paco Gento"]},
    {"year": "1958/59", "winner": "Real Madrid", "runnerUp": "Stade de Reims", "score": "2-0", "stadium": "Neckarstadion, Stoccarda", "coach": "Luis Carniglia", "roster": ["Rogelio Dominguez", "Marquitos", "Josamaria Zarraga", "Rafael Lesmes", "Juan Santisteban", "Antonio Ruiz", "Raymond Kopa", "Enrique Mateos", "Alfredo Di Stefano", "Héctor Rial", "Paco Gento"]},
    {"year": "1957/58", "winner": "Real Madrid", "runnerUp": "Milan", "score": "3-2 (dts)", "stadium": "Heysel Stadium, Bruxelles", "coach": "Luis Carniglia", "roster": ["Juan Alonso", "Atienza", "Marquitos", "Rafael Lesmes", "Juan Santisteban", "Josamaria Zarraga", "Raymond Kopa", "Joseito", "Alfredo Di Stefano", "Héctor Rial", "Paco Gento"]},
    {"year": "1956/57", "winner": "Real Madrid", "runnerUp": "Fiorentina", "score": "2-0", "stadium": "Santiago Bernabéu, Madrid", "coach": "José Villalonga", "roster": ["Juan Alonso", "Manuel Torres", "Marquitos", "Rafael Lesmes", "Miguel Muñoz", "Josamaria Zarraga", "Raymond Kopa", "Enrique Mateos", "Alfredo Di Stefano", "Héctor Rial", "Paco Gento"]},
    {"year": "1955/56", "winner": "Real Madrid", "runnerUp": "Stade de Reims", "score": "4-3", "stadium": "Parc des Princes, Parigi", "coach": "José Villalonga", "roster": ["Juan Alonso", "Atienza", "Marquitos", "Rafael Lesmes", "Miguel Muñoz", "Josamaria Zarraga", "Joseito", "Ramon Marsal", "Alfredo Di Stefano", "Héctor Rial", "Paco Gento"]}
];

const formatted_data = {};
for (const final of cl_finals) {
    const year = final.year;
    const roster_with_roles = [];
    
    // Simple heuristic to assign roles
    final.roster.forEach((p, i) => {
        let role = "POR";
        if (i > 0 && i < 5) role = "DIF";
        else if (i >= 5 && i < 8) role = "CEN";
        else if (i >= 8) role = "ATT";
            
        roster_with_roles.push({
            "name": p,
            "role": role,
            "isStarter": true
        });
    });
    
    formatted_data[year] = {
        "winner": final.winner,
        "runnerUp": final.runnerUp,
        "score": final.score,
        "stadium": final.stadium,
        "coach": final.coach,
        "stats": final.stats,
        "roster": roster_with_roles
    };
}

const out_path = path.join(__dirname, '..', 'src', 'data', 'rosters', 'champions_league.json');
fs.writeFileSync(out_path, JSON.stringify(formatted_data, null, 2), 'utf-8');

console.log("Generated full CL finals!");
